<?php

namespace Advanced_Product\Taxonomy;

use Advanced_Product\Taxonomy;

defined('ADVANCED_PRODUCT') or exit();

class Branch extends Taxonomy {

    public function hooks()
    {
        parent::hooks(); // TODO: Change the autogenerated stub

        add_action( 'admin_menu', array( $this, 'remove_taxonomy_metaboxes' ) );
    }

    public function register(){

        $singular  = __( 'Branch', $this -> text_domain );
        $plural    = __( 'Branches', $this -> text_domain );

        return array(
            'object_type'   => 'ap_product',
            'args'          => array(
                'label' 					=> $plural,
                'labels' => array(
                    'name' 					=> $singular,
                    'singular_name' 		=> $singular,
                    'menu_name'				=> $plural,
                    'search_items' 			=> sprintf( __( 'Search %s', $this -> text_domain ), $plural ),
                    'all_items' 			=> sprintf( __( 'All %s', $this -> text_domain ), $plural ),
                    'parent_item' 			=> sprintf( __( 'Parent %s', $this -> text_domain ), $singular ),
                    'parent_item_colon'		=> sprintf( __( 'Parent %s:', $this -> text_domain ), $singular ),
                    'edit_item' 			=> sprintf( __( 'Edit %s', $this -> text_domain ), $singular ),
                    'update_item' 			=> sprintf( __( 'Update %s', $this -> text_domain ), $singular ),
                    'add_new_item' 			=> sprintf( __( 'Add New %s', $this -> text_domain ), $singular ),
                    'new_item_name' 		=> sprintf( __( 'New %s Name', $this -> text_domain ),  $singular ),
                    'not_found' 		    => sprintf( __( 'No %s found.', $this -> text_domain ),  $plural ),
                ),
                'hierarchical'               => true,
                'show_admin_column'          => true,
                'exclude_from_search'          => true,
//                'query_var'                 => false,
            )
        );
    }

    /**
     * Removes the default taxonomy metaboxes from the edit screen.
     * We use the advanced custom fields instead and sync the data.
     */
    public function remove_taxonomy_metaboxes(){
        /* Remove meta box is tag */
        \remove_meta_box( 'tagsdiv-'.$this -> get_taxonomy_name(), 'ap_product', 'normal' );
        /* Remove meta box is category */
        \remove_meta_box( $this -> get_taxonomy_name().'div', 'ap_product', 'normal' );
    }
}