<?php

namespace Advanced_Product\Taxonomy;

use Advanced_Product\Taxonomy;

defined('ADVANCED_PRODUCT') or exit();

class Group_Field extends Taxonomy {

    protected $allow_custom_options = false;

    public function hooks()
    {
        parent::hooks(); // TODO: Change the autogenerated stub

        add_action( 'admin_menu', array( $this, 'admin_menu' ) );
        add_action( 'parent_file', array($this,'menu_highlight' ));
    }

    public function register(){

        $singular  = __( 'Custom Field Group', $this -> text_domain );
        $plural    = __( 'Custom Field Groups', $this -> text_domain );

        return array(
            'object_type'   => 'ap_custom_field',
            'args'          => array(
                'label' 					=> $plural,
                'labels' => array(
                    'name' 					=> $singular,
                    'singular_name' 		=> $singular,
                    'menu_name'				=> $plural,
                    'search_items' 			=> sprintf( __( 'Search %s', $this -> text_domain ), $plural ),
                    'all_items' 			=> sprintf( __( 'All %s', $this -> text_domain ), $plural ),
                    'parent_item' 			=> sprintf( __( 'Parent %s', $this -> text_domain ), $singular ),
                    'parent_item_colon'		=> sprintf( __( 'Parent %s:', $this -> text_domain ), $singular ),
                    'edit_item' 			=> sprintf( __( 'Edit %s', $this -> text_domain ), $singular ),
                    'update_item' 			=> sprintf( __( 'Update %s', $this -> text_domain ), $singular ),
                    'add_new_item' 			=> sprintf( __( 'Add New %s', $this -> text_domain ), $singular ),
                    'new_item_name' 		=> sprintf( __( 'New %s Name', $this -> text_domain ),  $singular ),
                    'not_found' 		    => sprintf( __( 'No %s found.', $this -> text_domain ),  $plural ),
                ),
                'hierarchical'              => true,
                'show_admin_column'         => true,
                'show_in_nav_menus'         => false,
//                'exclude_from_search' => true,
                'query_var' => false,
//                'publicly_queryable'        => false,
            )
        );
    }

    public function admin_menu(){
        add_submenu_page('edit.php?post_type=ap_product', 'Custom Field Groups',
            'Custom Field Groups', 'manage_options',
            'edit-tags.php?taxonomy='.$this -> get_taxonomy_name().'&post_type=ap_custom_field'/*,'bsp_students_add'*/);
    }

    /* Set menu highlight because wp not active */
    public function menu_highlight( $parent_file ) {
        global $submenu_file, $post_type, $taxonomy;

        if ( $taxonomy == $this -> get_taxonomy_name() && $post_type == 'ap_custom_field' ) {
            $parent_file = 'edit.php?post_type=ap_product';
            $submenu_file = 'edit-tags.php?taxonomy='.$this -> get_taxonomy_name().'&post_type=ap_custom_field';    // the submenu slug
        }

        return $parent_file;
    }
}